# Generated by Django 5.2.3 on 2025-11-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0003_movie_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='vote_count',
            field=models.IntegerField(null=True),
        ),
    ]
